### PR TITLE
BUG Fix broken createArgs() for scaffolded reads

### LINKED ISSUE #137: Adding args using scaffolding on code/config does not work.
https://github.com/silverstripe/silverstripe-graphql/tree/1.1#adding-arguments
I don't think this is working. It should be stated clearly in the documentation so that future users are not confused. 

IF it's in the roadmap, then perhaps note them somewhere as well. 

Use TypeCreator and QueryCreator if you want to use query arguments. 

# PRs:
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/138
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/111

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #137

After this is merged, you can merge https://github.com/silverstripe/silverstripe-versioned/pull/111

### CODE REVIEW

**Comment by tractorcow** [comment]
Nope, all the other operations are broken. Don't merge!

File: src/Scaffolding/Scaffolders/CRUD/Create.php [hunk 1]
```diff
@@ -2,22 +2,23 @@
...
 use SilverStripe\ORM\DataObject;
 use SilverStripe\ORM\DataObjectSchema;
 use SilverStripe\ORM\FieldType\DBField;
-use GraphQL\Type\Definition\Type;
 
 /**
  * A generic "create" operation for a DataObject.
  */
-class Create extends MutationScaffolder
+class Create extends MutationScaffolder implements ResolverInterface
```
Comment (unclecheese) [inline src/Scaffolding/Scaffolders/CRUD/Create.php]: I really like the idea of replacing the explicit assignment of a closure with something more pluggable, but I'd much prefer that these scaffolded operations take a `ResolverInterface` as a dependency.

```
private static $dependencies = [ 
  'Resolver' => '%$SilverStripe\GraphQL\Scaffolding\Interfaces\ResolverInterface.read'
];
```

In addition to allowing the operation to be customisable without  subclassing, it seems more consistent with the change we're trying to make, which is to make customising operations much better. This would put us in a position to make the API more composable, e.g.

```
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\Scaffolding\Interfaces\ResolverInterface.blogPostReadResolver
    class: MyProject\Resolvers\MyBlogResolver
  SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Read.blogPost
    properties:
      Resolver: %$SilverStripe\GraphQL\Scaffolding\Interfaces\ResolverInterface.blogPostReadResolver

Scaffolding:
  types:
     BlogPost:
       operations:
          read:
             service: SilverStripe\GraphQL\Scaffolding\Scaffolders\CRUD\Read.blogPost     
```

... or something to that effect. Just a thought.

File: src/Scaffolding/Scaffolders/CRUD/Create.php [hunk 2]
```diff
@@ -63,20 +47,13 @@ public function addToManager(Manager $manager)
         parent::addToManager($manager);
     }
 
-    /**
-     * @param Manager $manager
-     * @return array
-     */
-    protected function createArgs(Manager $manager)
+    protected function createDefaultArgs(Manager $manager)
```
Comment (unclecheese) [inline src/Scaffolding/Scaffolders/CRUD/Create.php]: I wonder if there's a better name for this. For me, it feels a bit in conflict with `setArgDefaults()`, which does something entirely different, but I could see someone thinking it influences this method.

File: src/Scaffolding/Scaffolders/CRUD/Read.php [hunk 3]
```diff
@@ -25,35 +28,7 @@ class Read extends ListQueryScaffolder
...
-     * @param Manager $manager
-     * @return array
-     */
-    protected function createArgs(Manager $manager)
-    {
-        $args = [];
-        $this->extend('updateArgs', $args, $manager);
-
-        return $args;
+        parent::__construct($this->createOperationName(), $this->typeName(), $this);
```
Comment (unclecheese) [inline src/Scaffolding/Scaffolders/CRUD/Read.php]: Passing `$this` to the parent constructor feels awfully awkward to me. I'd much rather see `createResolverFunction()` refactored:

```
if ($this instanceof ResolverInterface) {
  // .. just call class member
}
```

.. but as stated above, I think all of this is better served by a dependency.

File: src/Scaffolding/Scaffolders/CRUD/Update.php [hunk 4]
```diff
@@ -80,19 +52,16 @@ public function addToManager(Manager $manager)
      * @param Manager $manager
      * @return array
      */
-    protected function createArgs(Manager $manager)
+    protected function createDefaultArgs(Manager $manager)
     {
-        $args = [
+        return [
```
Comment (unclecheese) [inline src/Scaffolding/Scaffolders/CRUD/Update.php]: Just be aware that all of this will throw a merge conflict with the input type refactoring we put into master. https://github.com/silverstripe/silverstripe-graphql/issues/105

File: src/Scaffolding/Scaffolders/CRUD/Create.php (hunk 1 above)
Comment (tractorcow) [reply src/Scaffolding/Scaffolders/CRUD/Create.php]: Sure, but in this case the mutation is it's own resolver. Maybe another story?

File: src/Scaffolding/Scaffolders/CRUD/Create.php (hunk 2 above)
Comment (tractorcow) [reply src/Scaffolding/Scaffolders/CRUD/Create.php]: We can't set it because it depends on the $manager, it can only be late-resolved.

File: src/Scaffolding/Scaffolders/CRUD/Update.php (hunk 4 above)
Comment (tractorcow) [reply src/Scaffolding/Scaffolders/CRUD/Update.php]: I think it can be merged but it'll require a bit of manual work.
