### PR TITLE
FIX AbstractTypeRegistry should be able to handle scalar types (fixes #646)

### LINKED ISSUE #646: "Missing graphql file for Int" with latest webonyx/graphql-php version
### Module version(s) affected

5.3, 6.x

### Description

[`v15.31.0`](https://github.com/webonyx/graphql-php/releases/tag/v15.31.0) of `webonyx/graphql-php` has caused errors in our module, specifically [these changed lines](https://github.com/webonyx/graphql-php/commit/ef79ce18c14dd0d88bfc3a6c02a00f2adcbdf1bd#diff-8aeb029ad22e58e6a5dac793f8367eb5a28a1ba50a135de2904c6978762dfb0aR191-R205) (GitHub doesn’t auto-scroll for me, lines 191-205 of src/Type/Schema.php). The code now calls our type loader to check if we’ve overridden scalar types, it seems our type loader can’t currently handle this.

I don’t think it’s an issue in `webonyx/graphql-php` which is why I’ve raised it here: it seems to me that any type loader implementation should support loading scalar types.

### How to reproduce

`composer update` a Silverstripe 5 site to install `v15.31.0` of `webonyx/graphql-php`, then run a dev/build. You’ll see the error coming from the admin schema build process.

### Possible Solution

PR to come, workaround is to pin to `"webonyx/graphql-php": "15.30.2"`

### Additional Context

_No response_

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

### PR DESCRIPTION
**Pull request by lozcalver**
## Description
Updates `AbstractTypeRegistry` to support scalar types following [a change in `webonyx/graphql-php`](https://github.com/webonyx/graphql-php/commit/ef79ce18c14dd0d88bfc3a6c02a00f2adcbdf1bd)

## Manual testing steps
Run a dev/build with `webonyx/graphql-php: v15.31.0` or higher

## Issues

- #646

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

File: src/Schema/Storage/AbstractTypeRegistry.php [hunk 1]
```diff
@@ -139,6 +147,24 @@ protected static function fromCache(string $typename)
...
+    private static function hasRegistryScalarOverride(string $typename): bool
+    {
+        if (!method_exists(static::class, $typename)) {
+            return false;
+        }
+
+        // Override exists only when concrete registry implementation declares Int()/String() etc itself.
+        // Inherited methods from this abstract class don't count
+        $method = new ReflectionMethod(static::class, $typename);
+        return $method->getDeclaringClass()->getName() === static::class;
```
Comment (lozcalver) [inline src/Schema/Storage/AbstractTypeRegistry.php:165]: This method _seems_ unnecessary, because it looks like we could just do this instead as there are already methods in this class for each of the scalar types:

```php
if (method_exists(self::class, $typename)) {
    return call_user_func([self::class, $typename]);
}
```

That could lead to infinite recursion though. The generated code for the type loader (`.graphql-generated/__graphql-schema.php`) would look like this if the `Int` type was overridden:

```php
public static function Int() { return static::get('Int'); }
```

In normal operation, that would be a cache-hit inside the `get()` method and would return the generated `Int` file. But in the event of an exception, it would result in an infinite loop because `get('Int')` would call `static::Int()`, which would call `get('Int')` etc.

**Comment by lozcalver** [comment]
Hang fire on this pending the discussion in https://github.com/webonyx/graphql-php/issues/1874

**Review by emteknetnz — COMMENTED** [review]
Seems good, thanks for doing this

Note that the upstream webonyx fix https://github.com/webonyx/graphql-php/issues/1874 - which was released in  [v15.31.1](https://github.com/webonyx/graphql-php/releases/tag/v15.31.1) did not appear to fix issue, so we should merge this.

**Comment by lozcalver** [comment]
I think we could revert this now, [v15.31.2](https://github.com/webonyx/graphql-php/releases/tag/v15.31.2) has rolled back the change that caused problems with type loaders. So the code in this PR is essentially redundant (though won’t cause any harm)
