### PR TITLE
BUG Ensure queries are sorted before limiting

### LINKED ISSUE #199: BUG Connection limit / sort in wrong order
Checking the `Connection` class I noticed that sorting and limiting is done in the incorrect order; If applying both a sort and limit, the list is first limited, and then sorted.

When the base list is an in-memory list (rather than a DataList) this will limit first the un-sorted list, and then apply sorting only to the Nth page of the list.

With a datalist it's fine, because it's lazy-resolved, however.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #199

### CODE REVIEW

File: src/Pagination/Connection.php [hunk 1]
```diff
@@ -370,66 +370,84 @@ public function resolve($value, array $args, $context, ResolveInfo $info)
...
+
+        // convert the input from the input format of field, direction
+        // to an accepted SS_List sort format.
+        // https://github.com/graphql/graphql-relay-js/issues/20#issuecomment-220494222
+        $sort = [];
+        foreach ($sortBy as $sortInput) {
+            if (isset($sortInput['field'])) {
+                $direction = isset($sortInput['direction']) ? $sortInput['direction'] : 'ASC';
+                if (!array_key_exists($sortInput['field'], $sortableFields)) {
+                    throw new InvalidArgumentException(sprintf(
```
Comment (robbieaverill) [inline src/Pagination/Connection.php]: I think we should document this exception in the phpdoc

**Comment by robbieaverill** [comment]
I've merged this up to master @tractorcow
